spring:
  application:
    name: gateway
  banner:
    location: banner.txt
server:
  port: 8762

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

zuul:
  host:
    socket-timeout-millis: 30000
  routes:
    ams:
      serviceId: ams



#for stage and production
eureka:
  instance:
    hostname: gateway
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://naming-server:8761/eureka/
